# ---------------------------------------------------------
# Course: Time series analysis
# Exercise: 12th / ACF Case Studies
# Author: Felix Reichel
# ---------------------------------------------------------
require(astsa)
require(tseries)

# 1
plot(gtemp)
acf(gtemp)

# 2
plot(Nile)
acf(Nile)

# 3
plot(mdeaths)
acf(mdeaths)

plot(fdeaths)
acf(fdeaths)

# 4
plot(nyse)
acf(nyse)


# Q: which time-series could be generated by stationary process?