# ---------------------------------------------------------
# Course: Time series analysis
# Exercise: 12th / ACF Case Studies
# Author: Felix Reichel
# ---------------------------------------------------------
require(astsa)
require(tseries)

# def. (weakly) stationary: 
# I: µ(t) = µ 
# II: σ^2(t) = σ^2 
# III: γ(t, s) = γ(t − s)

# 1
plot(gtemp)
acf(gtemp)

# 2
plot(Nile)
acf(Nile)

# 3
plot(mdeaths)
acf(mdeaths)

plot(fdeaths)
acf(fdeaths)

# 4
plot(nyse)
acf(nyse)
acf(nyse, lag.max = 1000) # could be generated by a stationary process

